const projects = [
  {
    id: 1,
    slug: "wild-things",
    name: "Wild Things Nature Photography",
    projectDescription:
      "A website featuring Martin's wild life photography. The site is actively visited by over 1,000 patrons.",
    imageFile: "projects-1",
    repoUrl: "https://github.com/martindwyer/GoWildThings",
    liveUrl: "https://wildthings.mdbytes.us",
    featured: true,
    stack: [
      "React Framework",
      "JavaScript",
      "Lightbox",
      "GLightbox",
      "WordPress REST API",
      "PHP",
      "Apache",
      "MySQL",
      "Sass",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 2,
    slug: "primal-strength",
    name: "Primal Strength and Conditioning",
    projectDescription:
      "A website featuring Martin's work in the field of strength and conditioning. The site is actively visited by over 1,000 patrons.",
    imageFile: "projects-2",
    repoUrl: "https://github.com/martindwyer/PrimalStrength",
    liveUrl: "https://primal.mdbytes.us",
    featured: true,
    stack: [
      "React Framework",
      "JavaScript",
      "WordPress REST API",
      "PHP",
      "Apache",
      "MySQL",
      "Sass",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 3,
    slug: "feedback-focus",
    name: "Feedback Focus: Survey Generation, Transmission, Tabulation",
    projectDescription:
      "A web application which guides users through creation of surveys for their clients or propsects, emails the surveys, and tabulates the results as received.",
    imageFile: "projects-3",
    repoUrl: "https://github.com/martindwyer/FeedbackFocus",
    liveUrl: "https://customer-email-response-app.herokuapp.com/",
    featured: true,
    stack: [
      "MERN",
      "MongoDB",
      "Express",
      "Node",
      "React Framework",
      "Redux",
      "JavaScript",
      "WordPress REST API",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 4,
    slug: "expense-manager",
    name: "Expense Manager",
    projectDescription:
      "A web application which allows users to set up, track, and schedule expenses. Customizable based on user needs.",
    imageFile: "projects-4",
    repoUrl: "https://github.com/martindwyer/Expensify",
    liveUrl: "https://mdbytes-expensify-app.herokuapp.com/",
    featured: false,
    stack: [
      "React Framework",
      "Redux",
      "JavaScript",
      "Firebase",
      "Node",
      "Express",
      "Jest",
      "Sass",
      "CSS",
      "HTML",
    ],
  },
  {
    id: 5,
    slug: "employment-app",
    name: "Employment Application",
    projectDescription:
      "An interative web app to guide applicants through an employment application.  Customizeable to individual client needs.",
    imageFile: "projects-1",
    repoUrl: "https://github.com/martindwyer/EmploymentApplication",
    liveUrl: "https://careers.mdbytes.us",
    featured: false,
    stack: ["JavaScript", "CSS", "HTML", "Bootstrap Framework"],
  },
]

export default projects
